//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowCamp
{
    using System;
    
    public enum AnimationEnum : int
    {
        fence = 0,
        mouseCursor = 1,
        patrolRouteGreenGlyph = 2,
        brickWall = 3,
        concreteWall = 4,
        mouseCellCornerGlyph = 5,
        guardWalk = 6,
        prisonerWalk = 7,
        greenWall = 8,
        redWall = 9,
        guardShooting = 10,
        guardTurning = 11,
        prisonerDying = 12,
        sidePanels = 13,
        buttons = 14,
        patrolRouteRed = 15
    }
}
