//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowCamp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Animation()
        {
            this.CurrentAnimations = new HashSet<CurrentAnimation>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public string atlasName { get; set; }
        public int frameWidth { get; set; }
        public int frameHeight { get; set; }
        public int startX { get; set; }
        public int startY { get; set; }
        public AnimationEnum enumValue { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurrentAnimation> CurrentAnimations { get; set; }
    }
}
