//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowCamp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CellPartition
    {
        public int Id { get; set; }
        public int partitionMidPointX { get; set; }
        public int partitionMidPointY { get; set; }
    
        public virtual GameObject GameObject { get; set; }
    }
}
