//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowCamp
{
    using System;
    
    public enum GameObjectTypeEnum : int
    {
        fence = 0,
        brickWall = 1,
        mouseCursor = 2,
        mouseBuildGlyph = 3,
        concreteWall = 4,
        mouseCellCornerGlyph = 5,
        guard = 6,
        prisoner = 7
    }
}
