//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowCamp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatrolRoute
    {
        public int Id { get; set; }
        public int startCellX { get; set; }
        public int middleCellX { get; set; }
        public int endCellX { get; set; }
        public int startCellY { get; set; }
        public int middleCellY { get; set; }
        public int endCellY { get; set; }
        public int direction { get; set; }
        public int targetX { get; set; }
        public int targetY { get; set; }
    
        public virtual GameObject GameObject { get; set; }
    }
}
