//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowCamp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PowCampDatabaseModelContainer : DbContext
    {
        public PowCampDatabaseModelContainer()
            : base("name=PowCampDatabaseModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GameObject> GameObjects { get; set; }
        public virtual DbSet<GameObjectType> GameObjectTypes { get; set; }
        public virtual DbSet<InstantiatedGameObject> InstantiatedGameObjects { get; set; }
        public virtual DbSet<ScreenCoord> ScreenCoords { get; set; }
        public virtual DbSet<CellCoord> CellCoords { get; set; }
        public virtual DbSet<Scene> Scenes { get; set; }
        public virtual DbSet<ComponentDependency> ComponentDependencies { get; set; }
        public virtual DbSet<Level> Levels { get; set; }
        public virtual DbSet<SaveGame> SaveGames { get; set; }
        public virtual DbSet<CurrentAnimation> CurrentAnimations { get; set; }
        public virtual DbSet<Animation> Animations { get; set; }
        public virtual DbSet<Velocity> Velocities { get; set; }
        public virtual DbSet<Acceleration> Accelerations { get; set; }
        public virtual DbSet<Wall> Walls { get; set; }
        public virtual DbSet<PatrolRoute> PatrolRoutes { get; set; }
        public virtual DbSet<CellPartition> CellPartitions { get; set; }
        public virtual DbSet<Orientation> Orientations { get; set; }
        public virtual DbSet<TargetScreenCoord> TargetScreenCoords { get; set; }
        public virtual DbSet<PrevScreenCoord> PrevScreenCoords { get; set; }
        public virtual DbSet<TargetPathIndex> TargetPathIndexes { get; set; }
        public virtual DbSet<Guard> Guards { get; set; }
        public virtual DbSet<Health> Healths { get; set; }
        public virtual DbSet<Prisoner> Prisoners { get; set; }
        public virtual DbSet<RemovalMarker> RemovalMarkers { get; set; }
    }
}
