//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowCamp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PowCampDatabaseModelContainer : DbContext
    {
        public PowCampDatabaseModelContainer()
            : base("name=PowCampDatabaseModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GameObject> GameObjects { get; set; }
        public virtual DbSet<GameObjectType> GameObjectTypes { get; set; }
        public virtual DbSet<InstantiatedGameObject> InstantiatedGameObjects { get; set; }
        public virtual DbSet<ScreenCoord> ScreenCoord { get; set; }
        public virtual DbSet<CellCoord> CellCoord { get; set; }
        public virtual DbSet<Scene> Scenes { get; set; }
        public virtual DbSet<ComponentDependencies> ComponentDependencies { get; set; }
        public virtual DbSet<Level> Levels { get; set; }
        public virtual DbSet<SaveGame> SaveGames { get; set; }
        public virtual DbSet<Visible> Visibles { get; set; }
    }
}
