//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowCamp
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemovalMarker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RemovalMarker()
        {
            this.mustBeRemoved = false;
            this.timeSinceMarkedForRemoval = 0F;
            this.timeToRemoval = 0F;
        }
    
        public int Id { get; set; }
        public bool mustBeRemoved { get; set; }
        public float timeSinceMarkedForRemoval { get; set; }
        public float timeToRemoval { get; set; }
    
        public virtual GameObject GameObject { get; set; }
    }
}
